function updateTransit() {
    console.log("Updating data...")
    var plLoopTimes = document.getElementById("PlLoop").innerHTML = "<% plLoopTimes.forEach(function(eta){%><ol><%=moment(eta.arrT).format(\"h:mm A\")%><%setInterval(function(){moment(eta.arrT).format(\"h:mm A\")}, 60000)%><\/ol><%});%>"; //class for predicted arrival of Pink line Loop bound trains
    var pl54Times = document.getElementById("Pl54").innerHTML = "<% pl54Times.forEach(function(eta){%><ol><%=moment(eta.arrT).format(\"h:mm A\")%><%setInterval(function(){moment(eta.arrT).format(\"h:mm A\")}, 60000)%><\/ol><%});%>"; //class for predicted arrival of Pink line 54th/cermak bound trains
    var bus18East = document.getElementById("east18").innerHTML = "<%bus18East.forEach(function(eta){%> <ol><%if(eta.prdctdn != \"DUE\" || eta.length !=0){%><%=moment(new Date).add(eta.prdctdn, \'m\').format(\"h:mm A\")%><%}else {%><p>Sorry, no service is scheduled<\/p><% } %><\/ol><%});%>"; //class for predicted arrival of 18th eastbound buses
    var bus18West = document.getElementById("west18").innerHTML = "<%bus18West.forEach(function(eta){%> <ol><%if(eta.prdctdn != \"DUE\" || eta.length !=0){%><%=moment(new Date).add(eta.prdctdn, \'m\').format(\"h:mm A\")%><%}else {%><p>Sorry, no service is scheduled<\/p><% } %><\/ol><%});%>"; //class for predicted arrival of 18th westbound buses
    var bus60East = document.getElementById("east60").innerHTML = "<%bus60East.forEach(function(eta){%> <ol><%if(eta.prdctdn != \"DUE\" || eta.length !=0){%><%=moment(new Date).add(eta.prdctdn, \'m\').format(\"h:mm A\")%><%}else {%><p>Sorry, no service is scheduled<\/p><% } %><\/ol><%});%>"; //class for predicted arrival of 60 eastbound buses
    var bus60West = document.getElementById("west60").innerHTML = "<%bus60West.forEach(function(eta){%> <ol><%if(eta.prdctdn != \"DUE\" || eta.length !=0){%><%=moment(new Date).add(eta.prdctdn, \'m\').format(\"h:mm A\")%><%}else {%><p>Sorry, no service is scheduled<\/p><% } %><\/ol><%});%>"; //class for predicted arrival of 60 westbound buses
}
setInterval(updateTransit, 60000);